package com.agro.dkdlab.network.model


data class SampleList(
    val id: String,
    val stateCode: String? = null,
    val districtCode: String? = null,
    val tehsilCode: String? = null,
    val blockCode: String? = null,
    val villageCode: String? = null,
    val farmerPhoto: String? = null,
    val farmerName: String,
    val fatherName: String,
    val farmerMobileNumber: String,
    val khasraNumber: String,
    val villageName: String,
    val gender: String,
    val primaryPhone: String,
    val category: String,
    val farmSize: Double,
    val cropName: String,
    val irrigationSource: String,
    val latitude: Double,
    val longitude: Double,
    val ocValue: Any? = null,
    val phValue: Any? = null,
    val copperValue: Any? = null,
    val maganeseValue: Any? = null,
    val ironValue: Any? = null,
    val zincValue: Any? = null,
    val boronValue: Any? = null,
    val sulphurValue: Any? = null,
    val ocRangName: String,
    val phRangName: String,
    val copperRangName: Any? = null,
    val maganeseRangName: Any? = null,
    val ironRangName: Any? = null,
    val zincRangName: Any? = null,
    val boronRangName: Any? = null,
    val sulphurRangName: Any? = null,
    val creationDate: String,
    val creationTime: String,
    val message: String,
    val status: Boolean,
    val sampleBarCode: String,
    val stateName: String,
    val districtName: String,
    val tehsilName: Any? = null,
    val blockName: String,
    val pincode: String,
    val kvalue: Any? = null,
    val nvalue: Any? = null,
    val pvalue: Any? = null,
    val nrangName: String,
    val prangName: String,
    val krangName: String
)
